version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'financeiro'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-volume: