version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    ports: 
      - "3308:3306"
    environment: 
      - MYSQL_DATABASE=financeiro
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge