version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
  
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    ports: 
      - "3308:3306"
    environment: 
      - MYSQL_DATABASE=financeiro
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network

  nginx:
    build: docker/nginx
    container_name: nginx
    tty: true
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge